FROM mysql:5.7
COPY create-tk.hildebrandt.testcontainers.springboot.user-schema.sql /docker-entrypoint-initdb.d
#ENV MYSQL_DATABASE=userdb \
#MYSQL_USER=userdb \
#MYSQL_PASSWORD=test1234 \
#MYSQL_ROOT_PASSWORD=Test1234
#RUN mysql < /create-tk.hildebrandt.testcontainers.springboot.user-schema.sql